name: googleapis_generator_dependency

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  discoveryapis_generator:
    git: https://github.com/dart-lang/discoveryapis_generator.git
  io: ^0.3.3
  pool: ^1.4.0
  yaml: ^2.1.0
